services:
  db:
    image: postgres:15.1-alpine
    container_name: plataforma-ingressos-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    networks:
      - plataforma-ingressos-net
    volumes:
      - pg_data:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    restart: always

networks:
  plataforma-ingressos-net:
    driver: bridge

volumes:
  pg_data:
