FROM node:20-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml* ./

COPY prisma ./prisma

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3333

CMD ["sh", "-c", "test -f .env || cp .env.example .env && npx prisma db push && npx prisma db seed && pnpm dev"]